POST http://localhost:3001/push/subscribe
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJJc3R2YW4iLCJsYXN0TmFtZSI6IkthbG1hciIsImVtYWlsIjoia2FsbWFyaXN0dmFuMDc4QGdtYWlsLmNvbSIsIl9pZCI6IjY5OGE1OTIwMGI1Mzk5MWQxOGRiMmJmNiIsImlhdCI6MTc3MTM1MTQxMCwiZXhwIjoxNzcxOTU2MjEwfQ.PigII5sUNPlGJRN33UGdtVxQSuWtR-jl5KiHQuJszGc

{
    "endpoint": "https://fcm.googleapis.com/fcm/send/dgTdoqIYf2Q:APA91bFtdJgLUaQZZVmrCliNjAIU0q3lioWjhUIeHLu2QwHdPFPKRJxnRhMXWdq0pObqCDmb-tR8DssoPEfgf4kny6orvyhMuFkgHcK3lVete0YuL4u977cIvgJA0dN9p1qTowO5PeL6",
    "expirationTime": null,
    "keys": {
        "p256dh": "BJ3Vu4FgUoZRTIy8CXNs0XSvbuvXGVGHd6Tdz2pVacAZPQzl02qOBxyQZoIXAVu6KlQ-TbX4VENU6rCKxgcyYIs",
        "auth": "2UPdXn3VABc5iHPSnCD_Tg"
    }
}