GET http://localhost:3001/push/mysub
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJJc3R2YW4iLCJsYXN0TmFtZSI6IkthbG1hciIsImVtYWlsIjoia2FsbWFyaXN0dmFuMDc4QGdtYWlsLmNvbSIsIl9pZCI6IjY5OGE1OTIwMGI1Mzk5MWQxOGRiMmJmNiIsImlhdCI6MTc3MjA0ODQ4MywiZXhwIjoxNzcyNjUzMjgzfQ.-XmaEEqjet0H1Pp369Z6lxOztHDqi9J3yJ3xfpELfRw

{
    "endpoint": "https://fcm.googleapis.com/fcm/send/etj6yat-wk4:APA91bHJ_JCDrgbjfMOg4lBfebTVUWJdmPjcuEFRj9QrpmEp11rxL_KBl9G0s2e0jTFrun_aUBb5BkvgFy02P5XnCMYJY4DNtr0O89-Nbu7SP7k6CnFTXNnFqoHHaHjMt67uO_rN4RPb"
}